# Generated by Django 5.1.7 on 2025-04-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50, unique=True)),
                ('dep_description', models.CharField(max_length=50)),
                ('dep_Hod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_email', models.EmailField(max_length=254)),
                ('doc_DOJ', models.DateField()),
                ('doc_Que', models.CharField(max_length=50)),
                ('doc_contact', models.IntegerField()),
                ('doc_password', models.CharField(max_length=50)),
                ('doc_work', models.CharField(max_length=100)),
                ('doc_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.department', to_field='dep_name')),
            ],
        ),
    ]
