# Generated by Django 5.1.7 on 2025-04-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_DOJ', models.DateField()),
                ('emp_dep', models.CharField(max_length=50)),
                ('emp_contact', models.IntegerField()),
                ('emp_password', models.CharField(max_length=50)),
                ('emp_work', models.CharField(max_length=100)),
            ],
        ),
    ]
