# Generated by Django 5.1.7 on 2025-04-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='doc_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.department'),
        ),
    ]
