# Generated by Django 5.1.7 on 2025-04-25 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctordata_doc_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='doc_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.department', to_field='dep_name'),
        ),
    ]
