# Generated by Django 5.1.7 on 2025-04-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctordata_doc_name_patientdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='add_dep',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='patient_cpassword',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='patient_details',
        ),
        migrations.RemoveField(
            model_name='patientdata',
            name='select_doc',
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='doc_contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='patient_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=50)),
                ('P_email', models.EmailField(max_length=254)),
                ('P_address', models.CharField(max_length=50)),
                ('P_DOB', models.CharField(max_length=50)),
                ('P_contact', models.BigIntegerField()),
                ('P_details', models.CharField(max_length=100)),
                ('add_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.department', to_field='dep_name')),
                ('select_doc', models.ManyToManyField(to='hospital.doctordata')),
            ],
        ),
    ]
